/*
 * This source file was generated by the Gradle 'init' task
 */
package me.samuelh2005.java_mobile.libosmocom.gsup;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        // nothing to test yet
    }
}
